### PR TITLE
Add coverage badge to readme 

### PR DESCRIPTION
**Pull request by ambiknai**

### CODE REVIEW

**Review by arahamad — APPROVED** [review]
LGTM, lets see if it start showing build and coverage status

**Review by prankulmahajan — COMMENTED** [review]
The changes look fine. For script publishCoverage to work it expects branch "gh-pages" to be present, I think that is required before merging this PR.

**Comment by ambiknai** [comment]
Branch created.

**Review by prankulmahajan — APPROVED** [review]
LGTM

**Pull request merged**
